spring:

  datasource:
    driver-class-name: org.h2.Driver
    username: barros
    password: 70104
    url: jdbc:h2:file:./data/spring6jdbc3

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console